# dockerfile for biobakery metaphlan4

FROM python:3.10.9

LABEL maintainer="JIAJUN LIU"
LABEL description="AMILI shotgun metaphlan4"

ENV RELEASE_DATE=2023.09.30 \
	TZ=Asia/Singapore
ENV Python 3.10.9

# Download and install Anaconda3
RUN apt-get update && \
    apt-get install -y wget unzip fastqc && \
    wget https://repo.anaconda.com/archive/Anaconda3-2023.03-Linux-x86_64.sh -O anaconda.sh && \
    bash anaconda.sh -b -p /opt/conda && \
    rm anaconda.sh && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Add Anaconda3 to PATH
ENV PATH="/opt/conda/bin:${PATH}"

# Install Trimmomatic independent
RUN wget http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/Trimmomatic-0.39.zip && \
    unzip Trimmomatic-0.39.zip

### install biobakery 
RUN conda install -c conda-forge -c bioconda kneaddata metaphlan humann

# Run bash on container startup
CMD ["/bin/bash", "python"]
